-- Colunas em falta na tabela Bot (schema mais recente que as migrações existentes)
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "messageBuffer" INTEGER NOT NULL DEFAULT 1500;
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "asaasApiKey" TEXT;
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "userSplitType" TEXT NOT NULL DEFAULT 'PERCENTAGE';
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "userSplitValue" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "aiDetectionAction" TEXT NOT NULL DEFAULT 'PAUSE';
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "enableAiDetection" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "handoffPause" INTEGER NOT NULL DEFAULT 1440;
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "humanTakeoverPause" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "notifyChannels" TEXT NOT NULL DEFAULT 'INTERNAL,WHATSAPP,EMAIL';
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "connectToken" TEXT UNIQUE;
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "allowedGroups" TEXT[] DEFAULT '{}';
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "groupResponseMode" TEXT NOT NULL DEFAULT 'ALL';
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "masterId" TEXT;

-- FK masterId -> Bot (self-reference) para Agent Isolation
DO $$ BEGIN
  ALTER TABLE "Bot" ADD CONSTRAINT "Bot_masterId_fkey" FOREIGN KEY ("masterId") REFERENCES "Bot"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null; END $$;
