-- Bot columns in schema but missing from production DB
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "chatwootInboxId" TEXT;
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "aiAgentStatus" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "niche" TEXT NOT NULL DEFAULT 'GENERIC';
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "deliveryFeeType" TEXT NOT NULL DEFAULT 'FIXED';
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "deliveryFeeRules" JSONB DEFAULT '[]';
ALTER TABLE "Bot" ADD COLUMN IF NOT EXISTS "mapboxToken" TEXT;

-- Contact columns in schema but missing from production DB
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "contactType" TEXT NOT NULL DEFAULT 'CUSTOMER';
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "driverStatus" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "dispatchKeywords" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "activeJobs" INTEGER NOT NULL DEFAULT 0;
